import Ticket, {
  Priority, Status, Type, Via,
} from '../../src/models/Ticket';

const data: Ticket[] = [
  {
    _id: '1',
    url: 'http://url1',
    external_id: '1a',
    created_at: '',
    type: Type.Incident,
    subject: 'subject 1',
    description: 'how to work this plate?',
    priority: Priority.Low,
    status: Status.Open,
    submitter_id: 1,
    assignee_id: 2,
    organization_id: 2,
    tags: [],
    has_incidents: false,
    due_at: '',
    via: Via.Web,
  },
  {
    _id: '2',
    url: 'http://url2',
    external_id: '2a',
    created_at: '',
    type: Type.Incident,
    subject: 'subject 1',
    priority: Priority.Low,
    status: Status.Open,
    submitter_id: 1,
    assignee_id: 2,
    organization_id: 1,
    tags: ['tag1', 'tag2'],
    has_incidents: false,
    due_at: '',
    via: Via.Web,
  },
  {
    _id: '3',
    url: 'http://url3',
    external_id: '2a',
    created_at: '',
    type: Type.Incident,
    subject: 'subject 1',
    description: 'how to fix this noise?',
    priority: Priority.Low,
    status: Status.Open,
    submitter_id: 1,
    assignee_id: 2,
    organization_id: 200,
    tags: [],
    has_incidents: false,
    due_at: '',
    via: Via.Web,
  },
  {
    _id: '4',
    url: 'http://url4',
    external_id: '4a',
    created_at: '',
    type: Type.Incident,
    subject: 'subject 1',
    priority: Priority.Low,
    status: Status.Open,
    submitter_id: 1,
    assignee_id: 2,
    organization_id: 210,
    tags: [],
    has_incidents: false,
    due_at: '',
    via: Via.Web,
  },
];

export default data;
