import User, { Role } from '../../src/models/User';

const data: User[] = [
  {
    _id: 1,
    url: 'http://url1',
    external_id: '1a',
    name: 'user1',
    created_at: '',
    tags: [],
    active: true,
    shared: true,
    last_login_at: '',
    phone: '',
    signature: '',
    suspended: false,
    role: Role.Admin,
    email: '1@a.com',
  },
  {
    _id: 2,
    url: 'http://url2',
    external_id: '2a',
    name: 'org2',
    created_at: '',
    tags: ['tag1', 'tag2'],
    active: true,
    shared: true,
    last_login_at: '',
    phone: '',
    signature: '',
    suspended: false,
    role: Role.Admin,
    email: '2@b.com',
  },
  {
    _id: 3,
    url: 'http://url3',
    external_id: '2a',
    name: 'org3',
    created_at: '',
    tags: [],
    active: true,
    shared: true,
    last_login_at: '',
    phone: '',
    signature: '',
    suspended: false,
    role: Role.Agent,
  },
  {
    _id: 4,
    url: 'http://url4',
    external_id: '4a',
    name: 'org4',
    created_at: '',
    tags: [],
    active: true,
    shared: true,
    last_login_at: '',
    phone: '',
    signature: '',
    suspended: false,
    role: Role.EndUser,
    organization_id: 1,
  },
];

export default data;
